spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashopv2
    username: admin
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace # console에서 쿼리문 파라미터값 바로 출력
